name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^10.1.0
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  weather_icons: ^3.0.0
  fl_chart: ^0.65.0
  animate_do: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  simple_animations: ^5.0.2
  day_night_time_picker: ^1.3.0
  # weather_animation: ^1.0.0
  lottie: ^2.7.0  # Optional: for JSON animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/sunny.json
    - assets/animations/rainy.json
    - assets/animations/cloudy.json
    - assets/animations/snowy.json
